NDF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls',namespace="main")),
]

main/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login_user'),
    url(r'^login/$', views.LoginView.as_view(), name='login_user'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout_user'),
    url(r'^stud_profile/$', views.stud_profile, name='stud_profile'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^contact/$', views.contact, name='contact'),

    url(r'^no_dues_apply/$', views.no_dues_apply, name='no_dues_apply'),
    url(r'^stud_full_dept/$', views.stud_full_dept, name='stud_full_dept'),
    url(r'^stud_full_lab/$', views.stud_full_lab, name='stud_full_lab'),
    url(r'^faculty_profile/$', views.faculty_profile, name='faculty_profile'),
    url(r'^library_profile/$', views.library_profile, name='library_profile'),
    url(r'^caretaker_profile/$', views.caretaker_profile, name='caretaker_profile'),
    url(r'^gymkhana_profile/$', views.gymkhana_profile, name='gymkhana_profile'),
    url(r'^assireg_profile/$', views.assireg_profile, name='assireg_profile'),
    url(r'^warden_profile/$', views.warden_profile, name='warden_profile'),
    url(r'^onlinecc_profile/$', views.onlinecc_profile, name='onlinecc_profile'),
    url(r'^cc_profile/$', views.cc_profile, name='cc_profile'),
    url(r'^thesis_manager_profile/$', views.thesis_manager_profile, name='thesis_manager_profile'),
    url(r'^lab_profile/$', views.lab_profile, name='lab_profile'),
    url(r'^hod_profile/$', views.hod_profile, name='hod_profile'),
    url(r'^account_profile/$', views.account_profile, name='account_profile'),
    url(r'^search_faculties/$',views.search_faculties, name='search_faculties'),
    url(r'^add_faculty/$',views.add_faculty, name='add_faculty'),
    url(r'^update_status/$',views.update_status, name='update_status'),
    url(r'^update_remarks/$',views.update_remarks, name='update_remarks'),
    url(r'^update_status/$', views.update_status, name='update_status'),
    url(r'^update_remarks/$', views.update_remarks, name='update_remarks'),
    url(r'^update_lab_status/$', views.update_lab_status, name='update_lab_status'),
    url(r'^update_lab_remarks/$', views.update_lab_remarks, name='update_lab_remarks'),
    url(r'^update_faculty_status/$', views.update_faculty_status, name='update_faculty_status'),
    url(r'^update_faculty_remarks/$', views.update_faculty_remarks, name='update_faculty_remarks'),
    url(r'^search_students/$', views.search_students, name='search_students'),
    url(r'^add_student/$', views.add_student, name='add_student'),
    url(r'^delete_student/$', views.delete_student, name='delete_student'),

]

    #url(r'stud_profile/1$', views.stud_profile, names='stud_profile'),
    #url(r'^stud_profile/(?P<username>\w+)/', views.stud_profile, name='stud_overall'),
    #url(r'^stud_profile/(.*)/dept$', views.stud_full_dept, name='stud_dept'),
    #url(r'^stud_profile/(.*)/lab$',views.stud_full_lab , name='stud_lab'),


#index is view name

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from constants import * #LOGIN_SERVER, ROLES
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['name', 'webmail', 'department', 'hostel']


class FacultyForm(forms.ModelForm):

    class Meta:
        model = Faculty
        fields = ['webmail', 'department','name']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class LoginForm(forms.Form):
    username = forms.CharField(required=True, label='Webmail')
    password = forms.CharField(required=True, widget=forms.PasswordInput)
    login_server = forms.ChoiceField(required=True, choices=LOGIN_SERVER)
    role = forms.ChoiceField(required=True, choices=ROLES)

    def clean_role(self):
        valid_roles = [
       "Student", "Faculty", "Lab", "Caretaker", "Warden", "Gymkhana", "OnlineCC", "CC", "Thesis Manager", "Library", "Assistant Registrar", "HOD", "Account", "Admin"
        ]
        role = self.cleaned_data.get('role')
        if role not in valid_roles:
            raise  ValidationError(_('Invalid Role'), code='invalid')
        return role

    def clean_login_server(self):
        valid_servers = ['202.141.80.9', '202.141.80.10', '202.141.80.11',
                         '202.141.80.12', '202.141.80.13']
        login_server = self.cleaned_data.get('login_server')
        if login_server not in valid_servers:
            raise ValidationError(_('Invalid Login Server'), code='invalid')
        return login_server

main/views.py
from django.template import loader
from models import *
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response, get_object_or_404, redirect,reverse, HttpResponseRedirect
from django.db.models import Q
from datetime import datetime
from django.db.models.fields import DateTimeField
from django.utils import timezone
from forms import UserForm, LoginForm
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.urls import reverse_lazy
from django.utils.http import is_safe_url
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F

class LoginView(View):
    """
    View class for handling login functionality.
    """
    template_name = 'main/login.html'
    port = 995
    next = ''

    def get(self, request):
        self.next = request.GET.get('next', '')
        if request.user.is_authenticated() and not request.user.is_superuser:
            return redirect('/stud_profile')
        args = dict(form=LoginForm(None), next=self.next)
        return render(request, self.template_name, args)

    def post(self, request):
        redirect_to = request.POST.get('next', self.next)
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            server = form.cleaned_data.get('login_server')
            role = form.cleaned_data.get('role')
            print (role)

            user = auth.authenticate(username=username, password=password,
                                     server=server, port=self.port)
            if user is not None :
                if not is_safe_url(url=redirect_to, host=request.get_host()):
                    auth.login(request=request, user=user)
                    if role == "Student":
                        try:
                            student = Student.objects.get(webmail=username)
                        except Student.DoesNotExist:
                            student = None
                        if student is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_profile')
                    elif role == "Faculty":
                        try:
                            fac = Faculty.objects.get(webmail=username)
                        except Faculty.DoesNotExist:
                            fac = None
                        if fac is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/faculty_profile')
                    elif role == "Lab":
                        try:
                            lab = Lab.objects.get(webmail=username)
                        except Faculty.DoesNotExist:
                            lab = None
                        if lab is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/lab_profile')
                    elif role == "Caretaker":
                        try:
                            caretaker = Caretaker.objects.get(webmail=username)
                        except Caretaker.DoesNotExist:
                            caretaker = None
                        if caretaker is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/caretaker_profile')
                    elif role == "Warden":
                        try:
                            warden = Warden.objects.get(webmail=username)
                        except Warden.DoesNotExist:
                            warden = None
                        if warden is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/warden_profile')
                    elif role == "Gymkhana":
                        try:
                            gymnkhana = Gymkhana.objects.get(webmail=username)
                        except Gymkhana.DoesNotExist:
                            gymnkhana = None
                        if gymnkhana is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/gymkhana_profile')
                    elif role == "OnlineCC":
                        try:
                            onlinecc = OnlineCC.objects.get(webmail=username)
                        except OnlineCC.DoesNotExist:
                            onlinecc = None
                        if onlinecc is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/onlinecc_profile')
                    elif role == "CC":
                        try:
                            cc = CC.objects.get(webmail=username)
                        except CC.DoesNotExist:
                            cc = None
                        if cc is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/cc_profile')
                    elif role == "Thesis Manager":
                        try:
                            thesis_manager = SubmitThesis.objects.get(webmail=username)
                        except SubmitThesis.DoesNotExist:
                            thesis_manager = None
                        if thesis_manager is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/thesis_manager_profile')
                    elif role == "Library":
                        try:
                            library = Library.objects.get(webmail=username)
                        except Library.DoesNotExist:
                            library = None
                        if library is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/library_profile')
                    elif role == "Assistant Registrar":
                        try:
                            assistant_registrar = Assistant_registrar.objects.get(webmail=username)
                        except Assistant_registrar.DoesNotExist:
                            assistant_registrar = None
                        if assistant_registrar is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/assireg_profile')
                    elif role == "HOD":
                        try:
                            hod = HOD.objects.get(webmail=username)
                        except HOD.DoesNotExist:
                            hod = None
                        if hod is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/hod_profile')
                    elif role == "Account":
                        try:
                            account = Account.objects.get(webmail=username)
                        except Account.DoesNotExist:
                            account = None
                        if account is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/account_profile')
                    elif role == "Admin":
                        return redirect('/admin')
                else:
                    return redirect(redirect_to)
            else:
                form.add_error(None, 'No user exists for given credentials.')
                return render(request, self.template_name, dict(form=form))
        else:
            return render(request, self.template_name, dict(form=form))

class LogoutView(LoginRequiredMixin, View):
    """
    View class for handling logout.
    """
    login_url = reverse_lazy('login_user')
    raise_exception = False
    http_method_names = ['get', 'head', 'options']
    def get(self, request):
        auth.logout(request=request)
        return redirect('/')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        role = request.POST['role']
        print (role)
        user = authenticate(username=username, password=password)

main/templates/main/account.html
{% extends 'main/base.html' %}

{% block title %}
    {{ account.name }}|Account|Home Page
{% endblock %}

{% block name %}
    {{ account.name }}
{% endblock %}

{% block heading %}
    Students
{% endblock %}

{% block status_name %}"account_approval"{% endblock %}
{% block remarks_name %}"account_remarks"{% endblock %}
{% block studentlistpending %}
{% for stud in students %}
    {% if stud.account_approval is False %}
        <tr>
            <td>{{ stud.roll_no }}</td>
            <td>{{ stud.name }}</td>
            <td>{{ stud.webmail }}</td>
            <td>{{ stud.department }}</td>
            <td><input type="checkbox" onclick="update_status(this.id)" id="{{ stud.webmail }}"/></td>
            <td style="padding:0px; height:100%">
                <div style="height:100%" contenteditable id="{{ stud.roll_no }}" onkeyup="update_remarks(this.id)">{{ stud.account_remarks }}</div>
            </td>
            <td><span id="{{ stud.webmail }}time">{{ stud.account_update_time }}</span></td>
        </tr>
    {% endif %}
{% endfor %}
{% endblock %}

{% block studentlistapproved %}
{% for stud in students %}
    {% if stud.account_approval is True %}
        <tr>
            <td>{{ stud.roll_no }}</td>
            <td>{{ stud.name }}</td>
            <td>{{ stud.webmail }}</td>
            <td>{{ stud.department }}</td>
            <td><input type="checkbox" onclick="update_status(this.id)" checked id="{{ stud.webmail }}"/></td>
            <td style="padding:0px; height:100%">
               <div style="height:100%" contenteditable id="{{ stud.roll_no }}" onkeyup="update_remarks(this.id)">{{ stud.account_remarks }}</div>
            </td>
            <td><span id="{{ stud.webmail }}time">{{ stud.account_update_time }}</span></td>
        </tr>
    {% endif %}
{% endfor %}
{% endblock %}

main/templates/main/assistant_registrar.html
{% extends 'main/base.html' %}

{% block title %}
    {{ assistant_registrar.name }}|Assistant Registrar|Home Page
{% endblock %}

{% block name %}
    {{ assistant_registrar.name }}
{% endblock %}

{% block heading %}
    Students
{% endblock %}

{% block Status %}{{ stud.assistant_registrar_approval }}{% endblock %}
{% block Remarks%}{{ stud.assistant_registrar_remarks }}{% endblock %}
{%block Last_Updated%}{{ stud.assistant_registrar_update_time }}{% endblock %}
 {% block checkbox_init %}
     {% if stud.assistant_registrar_approval is True %}
         checked
     {% endif %}
 {% endblock %}
{% block status_name %}"assistant_registrar_approval"{% endblock %}
{% block remarks_name %}"assistant_registrar_remarks"{% endblock %}

{% block studentlistpending %}
{% for stud in students %}
    {% if stud.assistant_registrar_approval is False %}
        <tr>
            <td>{{ stud.roll_no }}</td>
            <td>{{ stud.name }}</td>
            <td>{{ stud.webmail }}</td>
            <td>{{ stud.department }}</td>
            <td><input type="checkbox" onclick="update_status(this.id)" id="{{ stud.webmail }}"/></td>
            <td style="padding:0px; height:100%">
                <div style="height:100%" contenteditable id="{{ stud.roll_no }}" onkeyup="update_remarks(this.id)">{{ stud.assistant_registrar_remarks }}</div>
            </td>
            <td><span id="{{ stud.webmail }}time">{{ stud.assistant_registrar_update_time }}</span></td>
        </tr>
    {% endif %}
{% endfor %}
{% endblock %}

{% block studentlistapproved %}
{% for stud in students %}
    {% if stud.assistant_registrar_approval is True %}
        <tr>
            <td>{{ stud.roll_no }}</td>
            <td>{{ stud.name }}</td>
            <td>{{ stud.webmail }}</td>
            <td>{{ stud.department }}</td>
            <td><input type="checkbox" onclick="update_status(this.id)" checked id="{{ stud.webmail }}"/></td>
            <td style="padding:0px; height:100%">
               <div style="height:100%" contenteditable id="{{ stud.roll_no }}" onkeyup="update_remarks(this.id)">{{ stud.assistant_registrar_remarks }}</div>
            </td>
            <td><span id="{{ stud.webmail }}time">{{ stud.assistant_registrar_update_time }}</span></td>
        </tr>
    {% endif %}
{% endfor %}
{% endblock %}

main/templates/main/rules.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Rules{{ student.name }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 10px;
            bottom: 0;
            width : 100%;
        position: fixed;
    }
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
      <h4>Welcome {{ student.name }}!</h4>
    <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
                <li><a href="{% url 'main:no_dues_apply' %}"> Dues Clear Application</a></li>
                <li><a  href="{% url 'main:stud_full_dept' %}">Professors detailed status</a></li>
                <li><a href="{% url 'main:stud_full_lab' %}"> Lab detailed status</a></li>
                <li class="active"><a href="{% url 'main:rules' %}">Instructions</a></li>
                <li><a href="{% url 'main:contact' %}">Contact</a></li>
                <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
      </ul><br>
    </div>
    <br>
    <div class="col-sm-9">
      <div class="well">
        <h4>Instructions :</h4>
            <p>Write instructions here </p>
      </div>
    </div>

    </div>
  </div>

<div id="wrapper">
		<div id="header"></div>
		<div id="content"></div>
		<div id="footer"></div>
	</div>
<footer class="container-fluid text-center">
 <p>&copy; 2017 IIT Guwahati</p>
    <p style="font-size:1.0em; text-align:center">Developed By :  &nbsp&nbsp <a href="https://www.facebook.com/meet.555.patoliya" style="color:#169FD8;text-decoration:none;">Meet Patoliya</a></p>
</footer>

</body>
</html>

main/templates/main/stud_full_lab.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Lab Detail of {{ student.name }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 10px;
            bottom: 0;
            width: 100%;
            position : fixed;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-3 sidenav hidden-xs">
            <h4>Welcome {{ student.name }}!</h4>
            <ul class="nav nav-pills nav-stacked">
                <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
                <li><a href="{% url 'main:no_dues_apply' %}"> Dues Clear Application</a></li>
                <li><a href="{% url 'main:stud_full_dept' %}">Professors detailed status</a></li>
                <li class="active"><a  href="{% url 'main:stud_full_lab' %}"> Lab detailed status</a></li>
                <li><a href="{% url 'main:rules' %}">Instructions</a></li>
                <li><a href="{% url 'main:contact' %}">Contact</a></li>
                <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
            </ul>
            <br>
        </div>
        <br>
        <div class="col-sm-9">
            <div class="well">
                <h4>Details of Labs and Workshops</h4>
            </div>
            <table id="lab_list" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Lab/Workshop</th>
                    <th>No Dues Status</th>
                    <th>Remarks</th>
                    <th>Last Updated</th>
                </tr>
                </thead>
                <tbody id="lablist">
                {% for labname, stat, remarks, time in details %}
                    <tr>
                        <td>
                            {{ labname }}
                        </td>
                        <td>
                            {% if stat is True %}
                                <span style="color: #11B54A">Approved</span>
                            {% else %}
                                <span style="color:#e92916">Not Approved</span>
                            {% endif %}
                        </td>
                        <td>
                            {{ remarks }}
                        </td>
                        <td>
                            {{ time }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>


        </div>
    </div>

</div>

<div id="wrapper">
    <div id="header"></div>
    <div id="content"></div>
    <div id="footer"></div>
</div>
<footer class="container-fluid text-center">
    <p>&copy; 2017 IIT Guwahati</p>
    <p style="font-size:1.0em; text-align:center">Developed By : &nbsp&nbsp <a
            href="https://www.facebook.com/meet.555.patoliya" style="color:#169FD8;text-decoration:none;">Meet
        Patoliya</a></p>
</footer>

</body>
</html>

main/templates/main/student_apply.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Apply | {{ student.name }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 10px;
            bottom: 0;
            width: 100%;
            position:fixed;
        }
    </style>

</head>
<body>
<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-3 sidenav hidden-xs">
            <h4>Welcome {{ student.name }}!</h4>
            <ul class="nav nav-pills nav-stacked">
                <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
                <li class="active"><a  href="{% url 'main:no_dues_apply' %}"> Dues Clear Application</a></li>
                <li><a href="{% url 'main:stud_full_dept' %}">Professors detailed status</a></li>
                <li><a href="{% url 'main:stud_full_lab' %}"> Lab detailed status</a></li>
                <li><a href="{% url 'main:rules' %}">Instructions</a></li>
                <li><a href="{% url 'main:contact' %}">Contact</a></li>
                <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
            </ul>
            <br>
        </div>
        <br>
        <div class="col-sm-9">
            <div class="well">
                <form class="form-horizontal" role="form" action="{% url 'main:no_dues_apply' %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3>Section to clear :</h3>
                    <div class="col-sm-9"><h4>Tick the sections to apply for clearing dues.</h4></div>
                    <div class="col-sm-9"><h6>*Add concerned faculties before applying for faculties
                        clarification</h6></div>
                    <br><br>
                    <br>
                    <br>

                    <div>

                        <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox"
                                                                             {% if student.library_process_trigger is True %}checked{% endif %}
                                                                             name="library_process_trigger">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Library
                        </p>
                        <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox"
                                                                             {% if student.cc_process_trigger is True %}checked{% endif %}
                                                                             name="cc_process_trigger">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CC
                        </p>
                        <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox"
                                                                             {% if student.dept_process_trigger is True %}checked{% endif %}
                                                                             name="dept_process_trigger">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Faculties*
                        </p>
                        <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox"
                                                                             {% if student.lab_process_trigger is True %}checked{% endif %}
                                                                             name="lab_process_trigger">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lab
                        </p>
                        <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox"
                                                                             {% if student.gymkhana_process_trigger is True %}checked{% endif %}
                                                                             name="gymkhana_process_trigger">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gymkhana
                        </p>
                        <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox"
                                                                             {% if student.hostel_process_trigger is True %}checked{% endif %}
                                                                             name="hostel_process_trigger">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hostel
                        </p>
                        <div class="col-sm-3">
                            <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-success">
                                Apply
                            </button>
                        </div>
                        <br><br><br>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<div id="wrapper">
    <div id="header"></div>
    <div id="content"></div>
    <div id="footer"></div>
</div>
<footer class="container-fluid text-center">
        <p>&copy; 2017 IIT Guwahati</p>
    <p style="font-size:1.0em; text-align:center">Developed By : &nbsp&nbsp <a
            href="https://www.facebook.com/meet.555.patoliya" style="color:#169FD8;text-decoration:none;">Meet
        Patoliya</a></p>
</footer>

</body>
</html>